From 8b7e0363f2f947ce37f1bd539c2730ebc5509820 Mon Sep 17 00:00:00 2001
From: David Steele <dsteele@gmail.com>
Date: Fri, 11 Oct 2013 22:13:13 -0400
Subject: [PATCH 21/21] Remove debug traceback to log on XMPP connect err

---
 cloudprint/cloudprint.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/cloudprint/cloudprint.py b/cloudprint/cloudprint.py
index 9f84fb9..a84600a 100755
--- a/cloudprint/cloudprint.py
+++ b/cloudprint/cloudprint.py
@@ -374,7 +374,7 @@ def process_jobs(cups_connection, cpp, printers):
 
         except:
             global FAIL_RETRY
-            LOGGER.exception('ERROR: Could not Connect to Cloud Service. Will Try again in %d Seconds' % FAIL_RETRY)
+            LOGGER.error('ERROR: Could not Connect to Cloud Service. Will Try again in %d Seconds' % FAIL_RETRY)
             time.sleep(FAIL_RETRY)
 
 
-- 
1.8.4.rc3

